# An example of ClusterConfig object with custom VPC IPv4 CIDR,
# and auto-allocated IPv6 CIDRs for all subnets; also without
# any nodegroups:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: skcc07715
  region: ap-southeast-2
  version: "1.18"

vpc:
  cidr: 10.15.0.0/16
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

nodeGroups: []
managedNodeGroups:
  - name: logging-node-mng
    tags:
      nodegroup-role: "logging"
      managed: "true"
    labels:
      role: logging
    instanceType: t3.large
    privateNetworking: true
    minSize: 3
    desiredCapacity: 4
    maxSize: 5
    volumeSize: 20
    ssh:
      allow: true

availabilityZones: ["ap-southeast-2a", "ap-southeast-2c"]
